db = db.getSiblingDB("mechdesign");

const mechResults = db.mechs.insertMany([
    {
        baseMech: 1,
        mechs_mechID: 1,
        mechs_mechName: "MadCat",
        mechs_armor: 120,
        mechs_maxTonnage: 75,
        mechs_introDate: 3025,
        mechs_mechModel: "Prime",
        mechs_era: "Star League",
        mechs_techBase: "Clan",
        mechs_productionYear: "3030",
        mecharmLeft_id: 3,
        mecharmRight_id: 5,
        mecharmLeft_mechID: 1,
        mecharmRight_mechID: 1,
        mecharmLeft_partLeftorRight: 0,
        mecharmRight_partLeftorRight: 1,
        mecharmLeft_slot1: "Medium ER Laser (Clan)",
        mecharmRight_slot1: "Medium ER Laser (Clan)",
        mecharmLeft_slot2: "Large ER Laser (Clan)",
        mecharmRight_slot2: "Large ER Laser (Clan)",
        mecharmLeft_slot3: "overflow",
        mecharmRight_slot3: "overflow",
        mecharmLeft_slot4: "",
        mecharmRight_slot4: "",
        mecharmLeft_slot5: "",
        mecharmRight_slot5: "",
        mecharmLeft_slot6: "",
        mecharmRight_slot6: "",
        mecharmLeft_slot7: "",
        mecharmRight_slot7: "",
        mecharmLeft_slot8: "",
        mecharmRight_slot8: "",
        mecharmLeft_slot9: "",
        mecharmRight_slot9: "",
        mecharmLeft_slot10: "",
        mecharmRight_slot10: "",
        mecharmLeft_slot11: "",
        mecharmRight_slot11: "",
        mecharmLeft_slot12: "",
        mecharmRight_slot12: "",
        mechengine_id: 1,
        mechengine_mechID: 1,
        mechengine_engineName: "XL Engine",
        mechengine_activeEngine: 1,
        mechengine_engineRating: 2,
        mechengine_mechWalk: 5,
        mechengine_mechRun: 8,
        mechengine_mechJump: 0,
        mechexternalarmor_id: 1,
        mechexternalarmor_mechID: 1,
        mechexternalarmor_armLeftArmor: 24,
        mechexternalarmor_armRightArmor: 24,
        mechexternalarmor_headArmor: 9,
        mechexternalarmor_centerArmor: 36,
        mechexternalarmor_rearCenterArmor: 9,
        mechexternalarmor_torsoLeftArmor: 25,
        mechexternalarmor_torsoRightArmor: 25,
        mechexternalarmor_rearLeftTorsoArmor: 7,
        mechexternalarmor_rearRightTorsoArmor: 7,
        mechexternalarmor_legLeftArmor: 32,
        mechexternalarmor_legRightArmor: 32,
        mechexternalarmor_mechArmorTotal: 230,
        mechhead_id: 1,
        mechhead_mechID: 1,
        mechhead_partLeftorRight: "2",
        mechhead_slot1: "Medium Pulse Laser (Clan)",
        mechhead_slot2: "",
        mechhead_slot3: "",
        mechhead_slot4: "",
        mechhead_slot5: "",
        mechhead_slot6: "",
        mechinternals_id: 1,
        mechinternals_mechID: 1,
        mechinternals_jumpJetsNum: 0,
        mechinternals_internalStructureTonnage: "4.0",
        mechinternals_engineTonnage: "19.5",
        mechinternals_gyroTonnage: "4.0",
        mechinternals_jumpJetsTonnage: "0.0",
        mechinternals_cockpitTonnage: "3.0",
        mechinternals_heatSinksTonnage: "7.0",
        mechinternals_totalInternalTonnage: "37.5",
        mechinternals_internalStructureCriticals: 25,
        mechinternals_engineCriticals: 12,
        mechinternals_gyroCriticals: 4,
        mechinternals_cockpitCriticals: 1,
        mechinternals_heatSinksCriticals: 7,
        mechinternals_enhancementsTonnage: 0,
        mechinternals_enhancementsCriticals: 0,
        mechinternals_jumpJetsCriticals: 0,
        mechinternals_heatSinkType: "Doubles",
        mechinternals_heatSinksNum: 17,
        mechinternals_weaponTonnage: 26,
        mechinternals_internalStructureType: "Endo Steel",
        mechlegLeft_id: 3,
        mechlegRight_id: 5,
        mechlegLeft_mechID: 1,
        mechlegRight_mechID: 1,
        mechlegLeft_partLeftorRight: 0,
        mechlegRight_partLeftorRight: 1,
        mechlegLeft_slot1: "",
        mechlegRight_slot1: "",
        mechlegLeft_slot2: "",
        mechlegRight_slot2: "",
        mechlegLeft_slot3: "",
        mechlegRight_slot3: "",
        mechlegLeft_slot4: "",
        mechlegRight_slot4: "",
        mechlegLeft_slot5: "",
        mechlegRight_slot5: "",
        mechlegLeft_slot6: "",
        mechlegRight_slot6: "",
        mechtorsoLeft_id: 1,
        mechtorsoRight_id: 3,
        mechtorsoLeft_mechID: 1,
        mechtorsoRight_mechID: 1,
        mechtorsoLeft_partLeftorRight: "0",
        mechtorsoRight_partLeftorRight: "1",
        mechtorsoLeft_slot1: "Machine Gun (Clan)",
        mechtorsoRight_slot1: "Machine Gun (Clan)",
        mechtorsoLeft_slot2: "LRM-20 (Clan)",
        mechtorsoRight_slot2: "LRM-20 (Clan)",
        mechtorsoLeft_slot3: "overflow",
        mechtorsoRight_slot3: "overflow",
        mechtorsoLeft_slot4: "LRM-20 Ammo (Clan)",
        mechtorsoRight_slot4: "LRM-20 Ammo (Clan)",
        mechtorsoLeft_slot5: "",
        mechtorsoRight_slot5: "",
        mechtorsoLeft_slot6: "",
        mechtorsoRight_slot6: "",
        mechtorsoLeft_slot7: "",
        mechtorsoRight_slot7: "",
        mechtorsoLeft_slot8: "",
        mechtorsoRight_slot8: "",
        mechtorsoLeft_slot9: "",
        mechtorsoRight_slot9: "",
        mechtorsoLeft_slot10: "",
        mechtorsoRight_slot10: "",
        mechtorsoLeft_slot11: "",
        mechtorsoRight_slot11: "",
        mechtorsoLeft_slot12: "",
        mechtorsoRight_slot12: "",
        mechtorsocenter_id: 1,
        mechtorsocenter_mechID: 1,
        mechtorsocenter_partLeftorRight: "2",
        mechtorsocenter_slot1: "Machine Gun Ammo (Clan)",
        mechtorsocenter_slot2: "Machine Gun Ammo (Clan)",
        mechtorsocenter_slot3: "",
        mechtorsocenter_slot4: "",
        mechtorsocenter_slot5: "",
        mechtorsocenter_slot6: "",
        mechtorsocenter_slot7: "",
        mechtorsocenter_slot8: "",
        mechtorsocenter_slot9: "",
        mechtorsocenter_slot10: "",
        mechtorsocenter_slot11: "",
        mechtorsocenter_slot12: "",
    },
    {
        baseMech: 1,
        mechs_mechID: 16,
        mechs_mechName: "MadDog",
        mechs_armor: 120,
        mechs_era: "Star League",
        mechs_introDate: 3025,
        mechs_maxTonnage: 60,
        mechs_mechModel: "Prime",
        mechs_productionYear: "3055",
        mechs_techBase: "Clan",
        mecharmLeft_id: 19,
        mecharmRight_id: 20,
        mecharmLeft_mechID: 16,
        mecharmRight_mechID: 16,
        mecharmLeft_partLeftorRight: 0,
        mecharmRight_partLeftorRight: 1,
        mecharmLeft_slot1: "Large Pulse Laser (Clan)",
        mecharmRight_slot1: "Large Pulse Laser (Clan)",
        mecharmLeft_slot10: "",
        mecharmRight_slot10: "",
        mecharmLeft_slot11: "",
        mecharmRight_slot11: "",
        mecharmLeft_slot12: "",
        mecharmRight_slot12: "",
        mecharmLeft_slot2: "overflow",
        mecharmRight_slot2: "overflow",
        mecharmLeft_slot3: "Medium Pulse Laser (Clan)",
        mecharmRight_slot3: "Medium Pulse Laser (Clan)",
        mecharmLeft_slot4: "",
        mecharmRight_slot4: "",
        mecharmLeft_slot5: "",
        mecharmRight_slot5: "",
        mecharmLeft_slot6: "",
        mecharmRight_slot6: "",
        mecharmLeft_slot7: "",
        mecharmRight_slot7: "",
        mecharmLeft_slot8: "",
        mecharmRight_slot8: "",
        mecharmLeft_slot9: "",
        mecharmRight_slot9: "",
        mechengine_activeEngine: 1,
        mechengine_engineName: "XL Engine",
        mechengine_engineRating: 2,
        mechengine_id: 9,
        mechengine_mechID: 16,
        mechengine_mechJump: 0,
        mechengine_mechRun: 8,
        mechengine_mechWalk: 5,
        mechexternalarmor_armLeftArmor: 16,
        mechexternalarmor_armRightArmor: 16,
        mechexternalarmor_centerArmor: 23,
        mechexternalarmor_headArmor: 9,
        mechexternalarmor_id: 9,
        mechexternalarmor_legLeftArmor: 23,
        mechexternalarmor_legRightArmor: 23,
        mechexternalarmor_mechArmorTotal: 163,
        mechexternalarmor_mechID: 16,
        mechexternalarmor_rearCenterArmor: 7,
        mechexternalarmor_rearLeftTorsoArmor: 7,
        mechexternalarmor_rearRightTorsoArmor: 7,
        mechexternalarmor_torsoLeftArmor: 16,
        mechexternalarmor_torsoRightArmor: 16,
        mechhead_id: 9,
        mechhead_mechID: 16,
        mechhead_partLeftorRight: "2",
        mechhead_slot1: "",
        mechhead_slot2: "",
        mechhead_slot3: "",
        mechhead_slot4: "",
        mechhead_slot5: "",
        mechhead_slot6: "",
        mechinternals_cockpitCriticals: 1,
        mechinternals_cockpitTonnage: "3.0",
        mechinternals_engineCriticals: 12,
        mechinternals_engineTonnage: "9.5",
        mechinternals_enhancementsCriticals: 0,
        mechinternals_enhancementsTonnage: 0,
        mechinternals_gyroCriticals: 4,
        mechinternals_gyroTonnage: "3.0",
        mechinternals_heatSinksCriticals: 2,
        mechinternals_heatSinksNum: 12,
        mechinternals_heatSinksTonnage: "2.0",
        mechinternals_heatSinkType: "Doubles",
        mechinternals_id: 9,
        mechinternals_internalStructureCriticals: 20,
        mechinternals_internalStructureTonnage: "6.0",
        mechinternals_internalStructureType: "Standard",
        mechinternals_jumpJetsCriticals: 0,
        mechinternals_jumpJetsNum: 0,
        mechinternals_jumpJetsTonnage: "0.0",
        mechinternals_mechID: 16,
        mechinternals_totalInternalTonnage: "23.5",
        mechinternals_weaponTonnage: 28,
        mechlegLeft_id: 19,
        mechlegRight_id: 20,
        mechlegLeft_mechID: 16,
        mechlegRight_mechID: 16,
        mechlegLeft_partLeftorRight: 0,
        mechlegRight_partLeftorRight: 1,
        mechlegLeft_slot1: "",
        mechlegRight_slot1: "",
        mechlegLeft_slot2: "",
        mechlegRight_slot2: "",
        mechlegLeft_slot3: "",
        mechlegRight_slot3: "",
        mechlegLeft_slot4: "",
        mechlegRight_slot4: "",
        mechlegLeft_slot5: "",
        mechlegRight_slot5: "",
        mechlegLeft_slot6: "",
        mechlegRight_slot6: "",
        mechtorsoLeft_id: 17,
        mechtorsoRight_id: 18,
        mechtorsoLeft_mechID: 16,
        mechtorsoRight_mechID: 16,
        mechtorsoLeft_partLeftorRight: "0",
        mechtorsoRight_partLeftorRight: "1",
        mechtorsoLeft_slot1: "LRM-20 (Clan)",
        mechtorsoRight_slot1: "LRM-20 (Clan)",
        mechtorsoLeft_slot10: "",
        mechtorsoRight_slot10: "",
        mechtorsoLeft_slot11: "",
        mechtorsoRight_slot11: "",
        mechtorsoLeft_slot12: "",
        mechtorsoRight_slot12: "",
        mechtorsoLeft_slot2: "overflow",
        mechtorsoRight_slot2: "overflow",
        mechtorsoLeft_slot3: "LRM-20 Ammo (Clan)",
        mechtorsoRight_slot3: "LRM-20 Ammo (Clan)",
        mechtorsoLeft_slot4: "",
        mechtorsoRight_slot4: "",
        mechtorsoLeft_slot5: "",
        mechtorsoRight_slot5: "",
        mechtorsoLeft_slot6: "",
        mechtorsoRight_slot6: "",
        mechtorsoLeft_slot7: "",
        mechtorsoRight_slot7: "",
        mechtorsoLeft_slot8: "",
        mechtorsoRight_slot8: "",
        mechtorsoLeft_slot9: "",
        mechtorsoRight_slot9: "",
        mechtorsocenter_id: 9,
        mechtorsocenter_mechID: 16,
        mechtorsocenter_partLeftorRight: "2",
        mechtorsocenter_slot1: "",
        mechtorsocenter_slot10: "",
        mechtorsocenter_slot11: "",
        mechtorsocenter_slot12: "",
        mechtorsocenter_slot2: "",
        mechtorsocenter_slot3: "",
        mechtorsocenter_slot4: "",
        mechtorsocenter_slot5: "",
        mechtorsocenter_slot6: "",
        mechtorsocenter_slot7: "",
        mechtorsocenter_slot8: "",
        mechtorsocenter_slot9: "",
    },
    {
        baseMech: 1,
        mechs_armor: 120,
        mechs_era: "Succession War",
        mechs_introDate: 3025,
        mechs_maxTonnage: 70,
        mechs_mechID: 18,
        mechs_mechModel: "WHM-6R",
        mechs_mechName: "Warhammer",
        mechs_productionYear: "3030",
        mechs_techBase: "Inner-Sphere",
        mecharmLeft_id: 23,
        mecharmRight_id: 24,
        mecharmLeft_mechID: 18,
        mecharmRight_mechID: 18,
        mecharmLeft_partLeftorRight: 0,
        mecharmRight_partLeftorRight: 1,
        mecharmLeft_slot1: "PPC",
        mecharmRight_slot1: "PPC",
        mecharmLeft_slot10: "",
        mecharmRight_slot10: "",
        mecharmLeft_slot11: "",
        mecharmRight_slot11: "",
        mecharmLeft_slot12: "",
        mecharmRight_slot12: "",
        mecharmLeft_slot2: "overflow",
        mecharmRight_slot2: "overflow",
        mecharmLeft_slot3: "overflow",
        mecharmRight_slot3: "overflow",
        mecharmLeft_slot4: "",
        mecharmRight_slot4: "",
        mecharmLeft_slot5: "",
        mecharmRight_slot5: "",
        mecharmLeft_slot6: "",
        mecharmRight_slot6: "",
        mecharmLeft_slot7: "",
        mecharmRight_slot7: "",
        mecharmLeft_slot8: "",
        mecharmRight_slot8: "",
        mecharmLeft_slot9: "",
        mecharmRight_slot9: "",
        mechengine_activeEngine: 1,
        mechengine_engineName: "Fusion Engine",
        mechengine_engineRating: 2,
        mechengine_id: 11,
        mechengine_mechID: 18,
        mechengine_mechJump: 0,
        mechengine_mechRun: 6,
        mechengine_mechWalk: 4,
        mechexternalarmor_armLeftArmor: 20,
        mechexternalarmor_armRightArmor: 20,
        mechexternalarmor_centerArmor: 22,
        mechexternalarmor_headArmor: 9,
        mechexternalarmor_id: 11,
        mechexternalarmor_legLeftArmor: 15,
        mechexternalarmor_legRightArmor: 15,
        mechexternalarmor_mechArmorTotal: 160,
        mechexternalarmor_mechID: 18,
        mechexternalarmor_rearCenterArmor: 9,
        mechexternalarmor_rearLeftTorsoArmor: 8,
        mechexternalarmor_rearRightTorsoArmor: 8,
        mechexternalarmor_torsoLeftArmor: 17,
        mechexternalarmor_torsoRightArmor: 17,
        mechhead_id: 11,
        mechhead_mechID: 18,
        mechhead_partLeftorRight: "2",
        mechhead_slot1: "",
        mechhead_slot2: "",
        mechhead_slot3: "",
        mechhead_slot4: "",
        mechhead_slot5: "",
        mechhead_slot6: "",
        mechinternals_cockpitCriticals: 1,
        mechinternals_cockpitTonnage: "3.0",
        mechinternals_engineCriticals: 12,
        mechinternals_engineTonnage: "16.0",
        mechinternals_enhancementsCriticals: 0,
        mechinternals_enhancementsTonnage: 0,
        mechinternals_gyroCriticals: 4,
        mechinternals_gyroTonnage: "3.0",
        mechinternals_heatSinksCriticals: 2,
        mechinternals_heatSinksNum: 18,
        mechinternals_heatSinksTonnage: "8.0",
        mechinternals_heatSinkType: "Singles",
        mechinternals_id: 11,
        mechinternals_internalStructureCriticals: 20,
        mechinternals_internalStructureTonnage: "7.0",
        mechinternals_internalStructureType: "Standard",
        mechinternals_jumpJetsCriticals: 0,
        mechinternals_jumpJetsNum: 0,
        mechinternals_jumpJetsTonnage: "0.0",
        mechinternals_mechID: 18,
        mechinternals_totalInternalTonnage: "37.0",
        mechinternals_weaponTonnage: 23,
        mechlegLeft_id: 23,
        mechlegRight_id: 24,
        mechlegLeft_mechID: 18,
        mechlegRight_mechID: 18,
        mechlegLeft_partLeftorRight: 0,
        mechlegRight_partLeftorRight: 1,
        mechlegLeft_slot1: "",
        mechlegRight_slot1: "",
        mechlegLeft_slot2: "",
        mechlegRight_slot2: "",
        mechlegLeft_slot3: "",
        mechlegRight_slot3: "",
        mechlegLeft_slot4: "",
        mechlegRight_slot4: "",
        mechlegLeft_slot5: "",
        mechlegRight_slot5: "",
        mechlegLeft_slot6: "",
        mechlegRight_slot6: "",
        mechtorsoLeft_id: 21,
        mechtorsoRight_id: 22,
        mechtorsoLeft_mechID: 18,
        mechtorsoRight_mechID: 18,
        mechtorsoLeft_partLeftorRight: "0",
        mechtorsoRight_partLeftorRight: "1",
        mechtorsoLeft_slot1: "Machine Gun",
        mechtorsoRight_slot1: "Machine Gun",
        mechtorsoLeft_slot10: "",
        mechtorsoRight_slot10: "",
        mechtorsoLeft_slot11: "",
        mechtorsoRight_slot11: "",
        mechtorsoLeft_slot12: "",
        mechtorsoRight_slot12: "",
        mechtorsoLeft_slot2: "Medium Laser",
        mechtorsoRight_slot2: "Medium Laser",
        mechtorsoLeft_slot3: "Small Laser",
        mechtorsoRight_slot3: "Small Laser",
        mechtorsoLeft_slot4: "",
        mechtorsoRight_slot4: "SRM-6",
        mechtorsoLeft_slot5: "",
        mechtorsoRight_slot5: "overflow",
        mechtorsoLeft_slot6: "",
        mechtorsoRight_slot6: "SRM-6 Ammo",
        mechtorsoLeft_slot7: "",
        mechtorsoRight_slot7: "",
        mechtorsoLeft_slot8: "",
        mechtorsoRight_slot8: "",
        mechtorsoLeft_slot9: "",
        mechtorsoRight_slot9: "",
        mechtorsocenter_id: 11,
        mechtorsocenter_mechID: 18,
        mechtorsocenter_partLeftorRight: "2",
        mechtorsocenter_slot1: "Machine Gun Ammo",
        mechtorsocenter_slot10: "",
        mechtorsocenter_slot11: "",
        mechtorsocenter_slot12: "",
        mechtorsocenter_slot2: "Machine Gun Ammo",
        mechtorsocenter_slot3: "",
        mechtorsocenter_slot4: "",
        mechtorsocenter_slot5: "",
        mechtorsocenter_slot6: "",
        mechtorsocenter_slot7: "",
        mechtorsocenter_slot8: "",
        mechtorsocenter_slot9: "",
    },
]);

Object.values(mechResults.insertedIds).forEach((id) => print("Inserted document ID: mechs:", id));

const quoteResults = db.quotes.insertMany([
    {
        quote: "I can't work miracles, sir! If you want an extra two tons of armor, you gotta lose two medium lasers.",
        docNum: "0",
        mechName: "MadCat",
        authorAndNote: "Sergeant Marty Rumble, 10th Lyran Guards",
    },
    {
        quote: "It's not the size of the mech that counts, it's how you use it!",
        docNum: "1",
        mechName: "Atlas",
        authorAndNote: "Captain Jax Slade, 2nd Battalion",
    },
    {
        quote: "Stay cool, stay calm, and keep firing.",
        docNum: "2",
        mechName: "Warhammer",
        authorAndNote: "Lieutenant Jenna Keeler, 9th Draconis Combine",
    },
    {
        quote: "No guts, no galaxy.",
        docNum: "3",
        mechName: "Timber Wolf",
        authorAndNote: "Star Colonel Aidan Pryde, Clan Jade Falcon",
    },
]);

Object.values(quoteResults.insertedIds).forEach((id) => print("Inserted document ID: quotes:", id));

const weapons = db.weapons.insertMany([
    {
        weaponName: "Autocannon 10",
        damage: "10",
        heat: "3",
        rangeMin: "0",
        rangeShort: "5",
        rangeMed: "10",
        rangeLong: "15",
        tons: "12",
        slotsRequired: "7",
        ammoNeeded: "Yes",
        weaponType: "Ballistics",
        availableDate: "3000",
        techBase: "Inner-Sphere",
    },
    {
        weaponName: "Autocannon 10 (Clan)",
        damage: "10",
        heat: "3",
        rangeMin: "0",
        rangeShort: "5",
        rangeMed: "10",
        rangeLong: "15",
        tons: "10",
        slotsRequired: "6",
        ammoNeeded: "Yes",
        weaponType: "Ballistics",
        availableDate: "3000",
        techBase: "Clan",
    },
    {
        weaponName: "Autocannon 10 Ammo",
        damage: "",
        heat: "",
        rangeMin: "",
        rangeShort: "",
        rangeMed: "",
        rangeLong: "",
        tons: "1",
        slotsRequired: "1",
        ammoNeeded: "",
        weaponType: "Ammunition",
        availableDate: "3000",
        techBase: "Inner-Sphere",
    },
    {
        weaponName: "Autocannon 2",
        damage: "2",
        heat: "1",
        rangeMin: "0",
        rangeShort: "8",
        rangeMed: "16",
        rangeLong: "24",
        tons: "6",
        slotsRequired: "1",
        ammoNeeded: "Yes",
        weaponType: "Ballistics",
        availableDate: "3000",
        techBase: "Inner-Sphere",
    },
    {
        weaponName: "Autocannon 2 (Clan)",
        damage: "2",
        heat: "1",
        rangeMin: "0",
        rangeShort: "8",
        rangeMed: "16",
        rangeLong: "24",
        tons: "5",
        slotsRequired: "1",
        ammoNeeded: "Yes",
        weaponType: "Ballistics",
        availableDate: "3000",
        techBase: "Clan",
    },
    {
        weaponName: "Autocannon 2 Ammo",
        damage: "",
        heat: "",
        rangeMin: "",
        rangeShort: "",
        rangeMed: "",
        rangeLong: "",
        tons: "1",
        slotsRequired: "1",
        ammoNeeded: "",
        weaponType: "Ammunition",
        availableDate: "3000",
        techBase: "Inner-Sphere",
    },
    {
        weaponName: "Autocannon 20",
        damage: "20",
        heat: "7",
        rangeMin: "0",
        rangeShort: "3",
        rangeMed: "6",
        rangeLong: "9",
        tons: "14",
        slotsRequired: "10",
        ammoNeeded: "Yes",
        weaponType: "Ballistics",
        availableDate: "3000",
        techBase: "Inner-Sphere",
    },
    {
        weaponName: "Autocannon 20 (Clan)",
        damage: "20",
        heat: "7",
        rangeMin: "0",
        rangeShort: "3",
        rangeMed: "6",
        rangeLong: "9",
        tons: "12",
        slotsRequired: "10",
        ammoNeeded: "Yes",
        weaponType: "Ballistics",
        availableDate: "3000",
        techBase: "Clan",
    },
    {
        weaponName: "Autocannon 20 Ammo",
        damage: "",
        heat: "",
        rangeMin: "",
        rangeShort: "",
        rangeMed: "",
        rangeLong: "",
        tons: "1",
        slotsRequired: "1",
        ammoNeeded: "",
        weaponType: "Ammunition",
        availableDate: "3000",
        techBase: "Inner-Sphere",
    },
    {
        weaponName: "Autocannon 5",
        damage: "5",
        heat: "1",
        rangeMin: "3",
        rangeShort: "6",
        rangeMed: "12",
        rangeLong: "18",
        tons: "8",
        slotsRequired: "4",
        ammoNeeded: "Yes",
        weaponType: "Ballistics",
        availableDate: "3000",
        techBase: "Inner-Sphere",
    },
    {
        weaponName: "Autocannon 5 (Clan)",
        damage: "5",
        heat: "1",
        rangeMin: "0",
        rangeShort: "6",
        rangeMed: "12",
        rangeLong: "18",
        tons: "6",
        slotsRequired: "3",
        ammoNeeded: "Yes",
        weaponType: "Ballistics",
        availableDate: "3000",
        techBase: "Clan",
    },
    {
        weaponName: "Autocannon 5 Ammo",
        damage: "",
        heat: "",
        rangeMin: "",
        rangeShort: "",
        rangeMed: "",
        rangeLong: "",
        tons: "1",
        slotsRequired: "1",
        ammoNeeded: "",
        weaponType: "Ammunition",
        availableDate: "3000",
        techBase: "Inner-Sphere",
    },
    {
        weaponName: "Flamer",
        damage: "2",
        heat: "3",
        rangeMin: "0",
        rangeShort: "1",
        rangeMed: "2",
        rangeLong: "3",
        tons: "0.5",
        slotsRequired: "1",
        ammoNeeded: "N/A",
        weaponType: "Energy",
        availableDate: "3000",
        techBase: "Inner-Sphere",
    },
    {
        weaponName: "Flamer (Clan)",
        damage: "2",
        heat: "3",
        rangeMin: "0",
        rangeShort: "1",
        rangeMed: "2",
        rangeLong: "3",
        tons: "0.5",
        slotsRequired: "1",
        ammoNeeded: "N/A",
        weaponType: "Energy",
        availableDate: "3000",
        techBase: "Clan",
    },
    {
        weaponName: "Large ER Laser (Clan)",
        damage: "10",
        heat: "12",
        rangeMin: "0",
        rangeShort: "8",
        rangeMed: "25",
        rangeLong: "40",
        tons: "4",
        slotsRequired: "2",
        ammoNeeded: "N/A",
        weaponType: "Energy",
        availableDate: "2825",
        techBase: "Clan",
    },
    {
        weaponName: "Large ER Laser (IS)",
        damage: "8",
        heat: "8",
        rangeMin: "0",
        rangeShort: "8",
        rangeMed: "15",
        rangeLong: "25",
        tons: "5",
        slotsRequired: "2",
        ammoNeeded: "N/A",
        weaponType: "Energy",
        availableDate: "3049",
        techBase: "Inner-Sphere",
    },
    {
        weaponName: "Large Laser",
        damage: "8",
        heat: "8",
        rangeMin: "0",
        rangeShort: "5",
        rangeMed: "10",
        rangeLong: "15",
        tons: "5",
        slotsRequired: "2",
        ammoNeeded: "N/A",
        weaponType: "Energy",
        availableDate: "3000",
        techBase: "Inner-Sphere",
    },
    {
        weaponName: "Large Laser (Clan)",
        damage: "8",
        heat: "8",
        rangeMin: "0",
        rangeShort: "5",
        rangeMed: "10",
        rangeLong: "15",
        tons: "4",
        slotsRequired: "1",
        ammoNeeded: "N/A",
        weaponType: "Energy",
        availableDate: "3000",
        techBase: "Clan",
    },
    {
        weaponName: "Large Pulse Laser (Clan)",
        damage: "10",
        heat: "10",
        rangeMin: "0",
        rangeShort: "7",
        rangeMed: "14",
        rangeLong: "21",
        tons: "6",
        slotsRequired: "2",
        ammoNeeded: "N/A",
        weaponType: "Energy",
        availableDate: "2825",
        techBase: "Clan",
    },
    {
        weaponName: "Large Pulse Laser (IS)",
        damage: "10",
        heat: "10",
        rangeMin: "0",
        rangeShort: "5",
        rangeMed: "10",
        rangeLong: "15",
        tons: "7",
        slotsRequired: "2",
        ammoNeeded: "N/A",
        weaponType: "Energy",
        availableDate: "3025",
        techBase: "Inner-Sphere",
    },
    {
        weaponName: "LRM-10",
        damage: "10",
        heat: "4",
        rangeMin: "6",
        rangeShort: "7",
        rangeMed: "14",
        rangeLong: "21",
        tons: "5",
        slotsRequired: "2",
        ammoNeeded: "Yes",
        weaponType: "Missiles",
        availableDate: "3000",
        techBase: "Inner-Sphere",
    },
    {
        weaponName: "LRM-10 (Clan)",
        damage: "10",
        heat: "4",
        rangeMin: "0",
        rangeShort: "7",
        rangeMed: "14",
        rangeLong: "21",
        tons: "2.5",
        slotsRequired: "2",
        ammoNeeded: "Yes",
        weaponType: "Missiles",
        availableDate: "3000",
        techBase: "Clan",
    },
    {
        weaponName: "LRM-10 Ammo",
        damage: "",
        heat: "",
        rangeMin: "",
        rangeShort: "",
        rangeMed: "",
        rangeLong: "",
        tons: "1",
        slotsRequired: "1",
        ammoNeeded: "",
        weaponType: "Ammunition",
        availableDate: "3000",
        techBase: "Inner-Sphere",
    },
    {
        weaponName: "LRM-10 Ammo (Clan)",
        damage: "",
        heat: "",
        rangeMin: "",
        rangeShort: "",
        rangeMed: "",
        rangeLong: "",
        tons: "1",
        slotsRequired: "1",
        ammoNeeded: "",
        weaponType: "Ammunition",
        availableDate: "3000",
        techBase: "Clan",
    },
    {
        weaponName: "LRM-15",
        damage: "15",
        heat: "5",
        rangeMin: "6",
        rangeShort: "7",
        rangeMed: "14",
        rangeLong: "21",
        tons: "7",
        slotsRequired: "3",
        ammoNeeded: "Yes",
        weaponType: "Missiles",
        availableDate: "3000",
        techBase: "Inner-Sphere",
    },
    {
        weaponName: "LRM-15 (Clan)",
        damage: "15",
        heat: "5",
        rangeMin: "0",
        rangeShort: "7",
        rangeMed: "14",
        rangeLong: "21",
        tons: "3.5",
        slotsRequired: "2",
        ammoNeeded: "Yes",
        weaponType: "Missiles",
        availableDate: "3000",
        techBase: "Clan",
    },
    {
        weaponName: "LRM-15 Ammo",
        damage: "",
        heat: "",
        rangeMin: "",
        rangeShort: "",
        rangeMed: "",
        rangeLong: "",
        tons: "1",
        slotsRequired: "1",
        ammoNeeded: "",
        weaponType: "Ammunition",
        availableDate: "3000",
        techBase: "Inner-Sphere",
    },
    {
        weaponName: "LRM-15 Ammo (Clan)",
        damage: "",
        heat: "",
        rangeMin: "",
        rangeShort: "",
        rangeMed: "",
        rangeLong: "",
        tons: "1",
        slotsRequired: "1",
        ammoNeeded: "",
        weaponType: "Ammunition",
        availableDate: "3000",
        techBase: "Clan",
    },
    {
        weaponName: "LRM-20",
        damage: "20",
        heat: "6",
        rangeMin: "6",
        rangeShort: "7",
        rangeMed: "14",
        rangeLong: "21",
        tons: "10",
        slotsRequired: "5",
        ammoNeeded: "Yes",
        weaponType: "Missiles",
        availableDate: "3000",
        techBase: "Inner-Sphere",
    },
    {
        weaponName: "LRM-20 (Clan)",
        damage: "20",
        heat: "6",
        rangeMin: "0",
        rangeShort: "7",
        rangeMed: "14",
        rangeLong: "21",
        tons: "5",
        slotsRequired: "2",
        ammoNeeded: "Yes",
        weaponType: "Missiles",
        availableDate: "3000",
        techBase: "Clan",
    },
    {
        weaponName: "LRM-20 Ammo",
        damage: "",
        heat: "",
        rangeMin: "",
        rangeShort: "",
        rangeMed: "",
        rangeLong: "",
        tons: "1",
        slotsRequired: "1",
        ammoNeeded: "",
        weaponType: "Ammunition",
        availableDate: "3000",
        techBase: "Inner-Sphere",
    },
    {
        weaponName: "LRM-20 Ammo (Clan)",
        damage: "",
        heat: "",
        rangeMin: "",
        rangeShort: "",
        rangeMed: "",
        rangeLong: "",
        tons: "1",
        slotsRequired: "1",
        ammoNeeded: "",
        weaponType: "Ammunition",
        availableDate: "3000",
        techBase: "Clan",
    },
    {
        weaponName: "LRM-5",
        damage: "5",
        heat: "2",
        rangeMin: "6",
        rangeShort: "7",
        rangeMed: "14",
        rangeLong: "21",
        tons: "2",
        slotsRequired: "2",
        ammoNeeded: "Yes",
        weaponType: "Missiles",
        availableDate: "3000",
        techBase: "Inner-Sphere",
    },
    {
        weaponName: "LRM-5 (Clan)",
        damage: "5",
        heat: "2",
        rangeMin: "0",
        rangeShort: "7",
        rangeMed: "14",
        rangeLong: "21",
        tons: "1",
        slotsRequired: "1",
        ammoNeeded: "Yes",
        weaponType: "Missiles",
        availableDate: "3000",
        techBase: "Clan",
    },
    {
        weaponName: "LRM-5 Ammo",
        damage: "",
        heat: "",
        rangeMin: "",
        rangeShort: "",
        rangeMed: "",
        rangeLong: "",
        tons: "1",
        slotsRequired: "1",
        ammoNeeded: "",
        weaponType: "Ammunition",
        availableDate: "3000",
        techBase: "Inner-Sphere",
    },
    {
        weaponName: "LRM-5 Ammo (Clan)",
        damage: "",
        heat: "",
        rangeMin: "",
        rangeShort: "",
        rangeMed: "",
        rangeLong: "",
        tons: "1",
        slotsRequired: "1",
        ammoNeeded: "",
        weaponType: "Ammunition",
        availableDate: "3000",
        techBase: "Clan",
    },
    {
        weaponName: "Machine Gun",
        damage: "2",
        heat: "0",
        rangeMin: "0",
        rangeShort: "1",
        rangeMed: "2",
        rangeLong: "3",
        tons: "0.5",
        slotsRequired: "1",
        ammoNeeded: "Yes",
        weaponType: "Ballistics",
        availableDate: "3000",
        techBase: "Inner-Sphere",
    },
    {
        weaponName: "Machine Gun (Clan)",
        damage: "2",
        heat: "0",
        rangeMin: "0",
        rangeShort: "1",
        rangeMed: "2",
        rangeLong: "3",
        tons: "0.25",
        slotsRequired: "1",
        ammoNeeded: "Yes",
        weaponType: "Ballistics",
        availableDate: "3000",
        techBase: "Clan",
    },
    {
        weaponName: "Machine Gun Ammo",
        damage: "",
        heat: "",
        rangeMin: "",
        rangeShort: "",
        rangeMed: "",
        rangeLong: "",
        tons: "0.5",
        slotsRequired: "1",
        ammoNeeded: "",
        weaponType: "Ammunition",
        availableDate: "3000",
        techBase: "Inner-Sphere",
    },
    {
        weaponName: "Machine Gun Ammo (Clan)",
        damage: "",
        heat: "",
        rangeMin: "",
        rangeShort: "",
        rangeMed: "",
        rangeLong: "",
        tons: "0.5",
        slotsRequired: "1",
        ammoNeeded: "",
        weaponType: "Ammunition",
        availableDate: "3000",
        techBase: "Clan",
    },
    {
        weaponName: "Medium ER Laser (Clan)",
        damage: "7",
        heat: "5",
        rangeMin: "0",
        rangeShort: "7",
        rangeMed: "14",
        rangeLong: "21",
        tons: "1",
        slotsRequired: "1",
        ammoNeeded: "N/A",
        weaponType: "Energy",
        availableDate: "2825",
        techBase: "Clan",
    },
    {
        weaponName: "Medium ER Laser (IS)",
        damage: "5",
        heat: "5",
        rangeMin: "0",
        rangeShort: "5",
        rangeMed: "10",
        rangeLong: "15",
        tons: "1",
        slotsRequired: "1",
        ammoNeeded: "N/A",
        weaponType: "Energy",
        availableDate: "3049",
        techBase: "Inner-Sphere",
    },
    {
        weaponName: "Medium Laser",
        damage: "5",
        heat: "3",
        rangeMin: "0",
        rangeShort: "3",
        rangeMed: "6",
        rangeLong: "9",
        tons: "1",
        slotsRequired: "1",
        ammoNeeded: "N/A",
        weaponType: "Energy",
        availableDate: "3000",
        techBase: "Inner-Sphere",
    },
    {
        weaponName: "Medium Laser (Clan)",
        damage: "5",
        heat: "3",
        rangeMin: "0",
        rangeShort: "3",
        rangeMed: "6",
        rangeLong: "9",
        tons: "1",
        slotsRequired: "1",
        ammoNeeded: "N/A",
        weaponType: "Energy",
        availableDate: "3000",
        techBase: "Clan",
    },
    {
        weaponName: "Medium Pulse Laser (Clan)",
        damage: "7",
        heat: "4",
        rangeMin: "0",
        rangeShort: "4",
        rangeMed: "8",
        rangeLong: "12",
        tons: "2",
        slotsRequired: "1",
        ammoNeeded: "N/A",
        weaponType: "Energy",
        availableDate: "2825",
        techBase: "Clan",
    },
    {
        weaponName: "Medium Pulse Laser (IS)",
        damage: "6",
        heat: "4",
        rangeMin: "0",
        rangeShort: "3",
        rangeMed: "6",
        rangeLong: "9",
        tons: "2",
        slotsRequired: "1",
        ammoNeeded: "N/A",
        weaponType: "Energy",
        availableDate: "3025",
        techBase: "Inner-Sphere",
    },
    {
        weaponName: "PPC",
        damage: "10",
        heat: "10",
        rangeMin: "3",
        rangeShort: "6",
        rangeMed: "12",
        rangeLong: "18",
        tons: "7",
        slotsRequired: "3",
        ammoNeeded: "N/A",
        weaponType: "Energy",
        availableDate: "3000",
        techBase: "Inner-Sphere",
    },
    {
        weaponName: "PPC (Clan)",
        damage: "10",
        heat: "10",
        rangeMin: "0",
        rangeShort: "6",
        rangeMed: "12",
        rangeLong: "18",
        tons: "6",
        slotsRequired: "2",
        ammoNeeded: "N/A",
        weaponType: "Energy",
        availableDate: "3000",
        techBase: "Clan",
    },
    {
        weaponName: "Small ER Laser (Clan)",
        damage: "5",
        heat: "2",
        rangeMin: "0",
        rangeShort: "3",
        rangeMed: "6",
        rangeLong: "9",
        tons: "0.5",
        slotsRequired: "1",
        ammoNeeded: "N/A",
        weaponType: "Energy",
        availableDate: "2825",
        techBase: "Clan",
    },
    {
        weaponName: "Small ER Laser (IS)",
        damage: "3",
        heat: "2",
        rangeMin: "0",
        rangeShort: "2",
        rangeMed: "4",
        rangeLong: "6",
        tons: "0.5",
        slotsRequired: "1",
        ammoNeeded: "N/A",
        weaponType: "Energy",
        availableDate: "3049",
        techBase: "Inner-Sphere",
    },
    {
        weaponName: "Small Laser",
        damage: "3",
        heat: "1",
        rangeMin: "0",
        rangeShort: "1",
        rangeMed: "2",
        rangeLong: "3",
        tons: "0.5",
        slotsRequired: "1",
        ammoNeeded: "N/A",
        weaponType: "Energy",
        availableDate: "3000",
        techBase: "Inner-Sphere",
    },
    {
        weaponName: "Small Laser (Clan)",
        damage: "3",
        heat: "1",
        rangeMin: "0",
        rangeShort: "1",
        rangeMed: "2",
        rangeLong: "3",
        tons: "0.5",
        slotsRequired: "1",
        ammoNeeded: "N/A",
        weaponType: "Energy",
        availableDate: "3000",
        techBase: "Clan",
    },
    {
        weaponName: "Small Pulse Laser (Clan)",
        damage: "3",
        heat: "2",
        rangeMin: "0",
        rangeShort: "3",
        rangeMed: "6",
        rangeLong: "9",
        tons: "0.5",
        slotsRequired: "1",
        ammoNeeded: "N/A",
        weaponType: "Energy",
        availableDate: "2825",
        techBase: "Clan",
    },
    {
        weaponName: "Small Pulse Laser (IS)",
        damage: "3",
        heat: "2",
        rangeMin: "0",
        rangeShort: "2",
        rangeMed: "4",
        rangeLong: "6",
        tons: "1",
        slotsRequired: "1",
        ammoNeeded: "N/A",
        weaponType: "Energy",
        availableDate: "3025",
        techBase: "Inner-Sphere",
    },
    {
        weaponName: "SRM-2",
        damage: "4",
        heat: "2",
        rangeMin: "0",
        rangeShort: "3",
        rangeMed: "6",
        rangeLong: "9",
        tons: "1",
        slotsRequired: "1",
        ammoNeeded: "Yes",
        weaponType: "Missiles",
        availableDate: "3000",
        techBase: "Inner-Sphere",
    },
    {
        weaponName: "SRM-2 (Clan)",
        damage: "4",
        heat: "2",
        rangeMin: "0",
        rangeShort: "3",
        rangeMed: "6",
        rangeLong: "9",
        tons: "0.5",
        slotsRequired: "1",
        ammoNeeded: "Yes",
        weaponType: "Missiles",
        availableDate: "3000",
        techBase: "Clan",
    },
    {
        weaponName: "SRM-2 Ammo",
        damage: "",
        heat: "",
        rangeMin: "",
        rangeShort: "",
        rangeMed: "",
        rangeLong: "",
        tons: "1",
        slotsRequired: "1",
        ammoNeeded: "",
        weaponType: "Ammunition",
        availableDate: "3000",
        techBase: "Inner-Sphere",
    },
    {
        weaponName: "SRM-2 Ammo (Clan)",
        damage: "",
        heat: "",
        rangeMin: "",
        rangeShort: "",
        rangeMed: "",
        rangeLong: "",
        tons: "1",
        slotsRequired: "1",
        ammoNeeded: "",
        weaponType: "Ammunition",
        availableDate: "3000",
        techBase: "Clan",
    },
    {
        weaponName: "SRM-4",
        damage: "8",
        heat: "3",
        rangeMin: "0",
        rangeShort: "3",
        rangeMed: "6",
        rangeLong: "9",
        tons: "2",
        slotsRequired: "1",
        ammoNeeded: "Yes",
        weaponType: "Missiles",
        availableDate: "3000",
        techBase: "Inner-Sphere",
    },
    {
        weaponName: "SRM-4 (Clan)",
        damage: "8",
        heat: "3",
        rangeMin: "0",
        rangeShort: "3",
        rangeMed: "6",
        rangeLong: "9",
        tons: "1",
        slotsRequired: "1",
        ammoNeeded: "Yes",
        weaponType: "Missiles",
        availableDate: "3000",
        techBase: "Clan",
    },
    {
        weaponName: "SRM-4 Ammo",
        damage: "",
        heat: "",
        rangeMin: "",
        rangeShort: "",
        rangeMed: "",
        rangeLong: "",
        tons: "1",
        slotsRequired: "1",
        ammoNeeded: "",
        weaponType: "Ammunition",
        availableDate: "3000",
        techBase: "Inner-Sphere",
    },
    {
        weaponName: "SRM-4 Ammo (Clan)",
        damage: "",
        heat: "",
        rangeMin: "",
        rangeShort: "",
        rangeMed: "",
        rangeLong: "",
        tons: "1",
        slotsRequired: "1",
        ammoNeeded: "",
        weaponType: "Ammunition",
        availableDate: "3000",
        techBase: "Clan",
    },
    {
        weaponName: "SRM-6",
        damage: "12",
        heat: "4",
        rangeMin: "0",
        rangeShort: "3",
        rangeMed: "6",
        rangeLong: "9",
        tons: "3",
        slotsRequired: "2",
        ammoNeeded: "Yes",
        weaponType: "Missiles",
        availableDate: "3000",
        techBase: "Inner-Sphere",
    },
    {
        weaponName: "SRM-6 (Clan)",
        damage: "12",
        heat: "4",
        rangeMin: "0",
        rangeShort: "3",
        rangeMed: "6",
        rangeLong: "9",
        tons: "1.5",
        slotsRequired: "1",
        ammoNeeded: "Yes",
        weaponType: "Missiles",
        availableDate: "3000",
        techBase: "Clan",
    },
    {
        weaponName: "SRM-6 Ammo",
        damage: "",
        heat: "",
        rangeMin: "",
        rangeShort: "",
        rangeMed: "",
        rangeLong: "",
        tons: "1",
        slotsRequired: "1",
        ammoNeeded: "",
        weaponType: "Ammunition",
        availableDate: "3000",
        techBase: "Inner-Sphere",
    },
    {
        weaponName: "SRM-6 Ammo (Clan)",
        damage: "",
        heat: "",
        rangeMin: "",
        rangeShort: "",
        rangeMed: "",
        rangeLong: "",
        tons: "1",
        slotsRequired: "1",
        ammoNeeded: "",
        weaponType: "Ammunition",
        availableDate: "3000",
        techBase: "Clan",
    },
    {
        weaponName: "Streak SRM-2 (Clan)",
        damage: "4",
        heat: "2",
        rangeMin: "0",
        rangeShort: "3",
        rangeMed: "6",
        rangeLong: "9",
        tons: "1",
        slotsRequired: "1",
        ammoNeeded: "Yes",
        weaponType: "Missiles",
        availableDate: "2825",
        techBase: "Clan",
    },
    {
        weaponName: "Streak SRM-2 (IS)",
        damage: "4",
        heat: "2",
        rangeMin: "0",
        rangeShort: "3",
        rangeMed: "6",
        rangeLong: "9",
        tons: "1.5",
        slotsRequired: "1",
        ammoNeeded: "Yes",
        weaponType: "Missiles",
        availableDate: "3045",
        techBase: "Inner-Sphere",
    },
    {
        weaponName: "Streak SRM-4 (Clan)",
        damage: "8",
        heat: "3",
        rangeMin: "0",
        rangeShort: "3",
        rangeMed: "6",
        rangeLong: "9",
        tons: "2",
        slotsRequired: "1",
        ammoNeeded: "Yes",
        weaponType: "Missiles",
        availableDate: "2825",
        techBase: "Clan",
    },
    {
        weaponName: "Streak SRM-4 (IS)",
        damage: "8",
        heat: "3",
        rangeMin: "0",
        rangeShort: "3",
        rangeMed: "6",
        rangeLong: "9",
        tons: "2.5",
        slotsRequired: "1",
        ammoNeeded: "Yes",
        weaponType: "Missiles",
        availableDate: "3045",
        techBase: "Inner-Sphere",
    },
    {
        weaponName: "Streak SRM-6 (Clan)",
        damage: "12",
        heat: "4",
        rangeMin: "0",
        rangeShort: "3",
        rangeMed: "6",
        rangeLong: "9",
        tons: "3",
        slotsRequired: "2",
        ammoNeeded: "Yes",
        weaponType: "Missiles",
        availableDate: "2825",
        techBase: "Clan",
    },
    {
        weaponName: "Streak SRM-6 (IS)",
        damage: "12",
        heat: "4",
        rangeMin: "0",
        rangeShort: "3",
        rangeMed: "6",
        rangeLong: "9",
        tons: "4.5",
        slotsRequired: "2",
        ammoNeeded: "Yes",
        weaponType: "Missiles",
        availableDate: "3045",
        techBase: "Inner-Sphere",
    },
    {
        weaponName: "Vehicle Flamer",
        damage: "2",
        heat: "3",
        rangeMin: "0",
        rangeShort: "1",
        rangeMed: "2",
        rangeLong: "3",
        tons: "0.5",
        slotsRequired: "1",
        ammoNeeded: "Yes",
        weaponType: "Energy",
        availableDate: "3000",
        techBase: "Inner-Sphere",
    },
    {
        weaponName: "Vehicle Flamer Ammo",
        damage: "",
        heat: "",
        rangeMin: "",
        rangeShort: "",
        rangeMed: "",
        rangeLong: "",
        tons: "1",
        slotsRequired: "1",
        ammoNeeded: "",
        weaponType: "Ammunition",
        availableDate: "3000",
        techBase: "Inner-Sphere",
    },
]);
